name: Spencer CI/CD

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Spencer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Register Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -az --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='docker/' \
            --exclude='docker-compose.yml' \
            ./ \
            ${{ vars.USERNAME }}@${{ vars.HOST }}:/var/www/spencer/
